In [1]:
import pandas as pd
import numpy as np

In [2]:
training_df = pd.read_csv('datasets/training_df.csv')
index_range_df = pd.read_csv('datasets/instance_cluster_indices.csv', index_col=0)

In [3]:
instances = training_df.inst_num.astype('int')
instances

0           1
1          16
2          16
3          16
4          16
           ..
1367426    50
1367427    50
1367428    50
1367429    50
1367430    50
Name: inst_num, Length: 1367431, dtype: int64

In [4]:
cluster_index_list = list()
for idx in range(len(index_range_df)):
    current_inst_num = index_range_df.iloc[idx, 0]
    current_cluster = index_range_df.iloc[idx, 1]
    cluster_index_list.append((current_inst_num, current_cluster))
cluster_index_list

[(1, 1),
 (2, 2),
 (3, 2),
 (4, 2),
 (5, 2),
 (6, 2),
 (7, 2),
 (8, 2),
 (9, 3),
 (10, 3),
 (11, 3),
 (12, 3),
 (13, 3),
 (14, 3),
 (15, 3),
 (16, 3),
 (17, 3),
 (18, 3),
 (19, 3),
 (20, 3),
 (21, 3),
 (22, 3),
 (23, 4),
 (24, 4),
 (25, 4),
 (26, 4),
 (27, 4),
 (28, 4),
 (29, 4),
 (30, 4),
 (31, 4),
 (32, 4),
 (35, 4),
 (36, 4),
 (37, 4),
 (40, 5),
 (41, 5),
 (43, 5),
 (44, 5),
 (45, 5),
 (48, 5),
 (50, 5),
 (51, 5),
 (55, 5),
 (57, 5),
 (58, 5),
 (59, 5),
 (60, 5),
 (61, 5),
 (64, 5),
 (70, 6),
 (80, 6),
 (81, 6),
 (85, 6),
 (90, 7),
 (99, 7),
 (100, 7),
 (120, 7),
 (128, 8),
 (130, 8),
 (140, 8),
 (150, 8),
 (160, 8),
 (180, 9),
 (200, 9),
 (250, 9),
 (256, 9),
 (300, 9),
 (400, 10),
 (500, 10),
 (512, 10),
 (600, 10),
 (800, 10)]

In [5]:
ranges = list()
cluster_change = 0
for tup in cluster_index_list:
    num_inst, cluster_index = tup
    if cluster_index != cluster_change:
        cluster_change = cluster_index
        ranges.append(num_inst)
ranges

[1, 2, 9, 23, 40, 70, 90, 128, 180, 400]

In [6]:
ranges: np.ndarray = np.array([1, 2, 9, 23, 40, 70, 90, 128, 180, 400])

In [7]:
(ranges >= 2)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [8]:
instances.values

array([ 1, 16, 16, ..., 50, 50, 50])

In [9]:
ranges: np.ndarray = np.array([1, 2, 9, 23, 40, 70, 90, 128, 180, 400])
def get_cluster_index(instance_number: int) -> int:
    
    # for idx, r in enumerate(ranges):
    #     if instance_number <= r:
    #         return idx
    return -1

In [10]:
ranges >= 2

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [11]:
from typing import List


def get_index_pos(bool_array: np.bool_) -> int:
    val =  np.where(bool_array == True)
    if val[0].size == 0:
        return 10
    return val[0][0]

index_pos_vec = np.vectorize(get_index_pos)

In [12]:
bool_list = np.bool_([0, 1, 1, 1])
# print(bool_list.shape)
get_index_pos(bool_list)

1

In [13]:
bool_list_test = np.bool_([0, 0])
get_index_pos(bool_list_test)

10

In [17]:
instances

0           1
1          16
2          16
3          16
4          16
           ..
1367426    50
1367427    50
1367428    50
1367429    50
1367430    50
Name: inst_num, Length: 1367431, dtype: int64

In [16]:
instance_indices = instances.apply(lambda x: get_index_pos(x <= ranges))
type(instance_indices)

pandas.core.series.Series

In [18]:
instance_indices

0          0
1          3
2          3
3          3
4          3
          ..
1367426    5
1367427    5
1367428    5
1367429    5
1367430    5
Name: inst_num, Length: 1367431, dtype: int64

In [ ]:

instance_indices_series = pd.Series(instance_indices)

In [19]:
dummies = pd.get_dummies(instance_indices)
type(dummies)

pandas.core.frame.DataFrame

In [28]:

dummies.rename(columns={col: f'inst_clust_{col}' for col in dummies.columns}, inplace=True)
dummies

inst_clust_0  inst_clust_1  inst_clust_2  inst_clust_3  inst_clust_4  \
0                   1             0             0             0             0   
1                   0             0             0             1             0   
2                   0             0             0             1             0   
3                   0             0             0             1             0   
4                   0             0             0             1             0   
...               ...           ...           ...           ...           ...   
1367426             0             0             0             0             0   
1367427             0             0             0             0             0   
1367428             0             0             0             0             0   
1367429             0             0             0             0             0   
1367430             0             0             0             0             0   

         inst_clust_5  inst_clust_6  inst_clust_7  inst_clust_8  inst_clust_9  \
0                   0             0             0             0             0   
1                   0             0             0             0             0   
2                   0             0             0             0             0   
3                   0             0             0             0             0   
4                   0             0             0             0             0   
...               ...           ...           ...           ...           ...   
1367426             1             0             0             0             0   
1367427             1             0             0             0             0   
1367428             1             0             0             0             0   
1367429             1             0             0             0             0   
1367430             1             0             0             0             0   

         inst_clust_10  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  
...                ...  
1367426              0  
1367427              0  
1367428              0  
1367429              0  
1367430              0  

[1367431 rows x 11 columns]

In [29]:
inst_df = training_df.join(dummies)


In [55]:
print(inst_df.iloc[:3,27:31].to_latex(index=True, multirow=True, multicolumn=True))

\begin{tabular}{lrrrr}
\toprule
{} &  inst\_clust\_0 &  inst\_clust\_1 &  inst\_clust\_2 &  inst\_clust\_3 \\
\midrule
0 &             1 &             0 &             0 &             0 \\
1 &             0 &             0 &             0 &             1 \\
2 &             0 &             0 &             0 &             1 \\
\bottomrule
\end{tabular}



/var/folders/dj/hxzphr3j0617vybm1xdwl_tw0000gn/T/ipykernel_62727/1584129217.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  print(inst_df.iloc[:3,27:31].to_latex(index=True, multirow=True, multicolumn=True))


In [108]:
inst_df.to_csv('datasets/df_instance.csv')