In [3]:
import pandas as pd
import numpy as np

In [4]:
training_df = pd.read_csv('datasets/training_df.csv')
index_range_df = pd.read_csv('datasets/instance_cluster_indices.csv', index_col=0)

In [5]:
instances = training_df.inst_num.astype('int')
instances

0           1
1          16
2          16
3          16
4          16
           ..
1367426    50
1367427    50
1367428    50
1367429    50
1367430    50
Name: inst_num, Length: 1367431, dtype: int64

In [6]:
cluster_index_list = list()
for idx in range(len(index_range_df)):
    current_inst_num = index_range_df.iloc[idx, 0]
    current_cluster = index_range_df.iloc[idx, 1]
    cluster_index_list.append((current_inst_num, current_cluster))
cluster_index_list

[(1, 1),
 (2, 2),
 (3, 2),
 (4, 2),
 (5, 2),
 (6, 2),
 (7, 2),
 (8, 2),
 (9, 3),
 (10, 3),
 (11, 3),
 (12, 3),
 (13, 3),
 (14, 3),
 (15, 3),
 (16, 3),
 (17, 3),
 (18, 3),
 (19, 3),
 (20, 3),
 (21, 3),
 (22, 3),
 (23, 4),
 (24, 4),
 (25, 4),
 (26, 4),
 (27, 4),
 (28, 4),
 (29, 4),
 (30, 4),
 (31, 4),
 (32, 4),
 (35, 4),
 (36, 4),
 (37, 4),
 (40, 5),
 (41, 5),
 (43, 5),
 (44, 5),
 (45, 5),
 (48, 5),
 (50, 5),
 (51, 5),
 (55, 5),
 (57, 5),
 (58, 5),
 (59, 5),
 (60, 5),
 (61, 5),
 (64, 5),
 (70, 6),
 (80, 6),
 (81, 6),
 (85, 6),
 (90, 7),
 (99, 7),
 (100, 7),
 (120, 7),
 (128, 8),
 (130, 8),
 (140, 8),
 (150, 8),
 (160, 8),
 (180, 9),
 (200, 9),
 (250, 9),
 (256, 9),
 (300, 9),
 (400, 10),
 (500, 10),
 (512, 10),
 (600, 10),
 (800, 10)]

In [7]:
ranges = list()
cluster_change = 0
for tup in cluster_index_list:
    num_inst, cluster_index = tup
    if cluster_index != cluster_change:
        cluster_change = cluster_index
        ranges.append(num_inst)
ranges

[1, 2, 9, 23, 40, 70, 90, 128, 180, 400]

In [8]:
ranges: np.ndarray = np.array([1, 2, 9, 23, 40, 70, 90, 128, 180, 400])

In [9]:
(ranges >= 2)

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [10]:
instances.values

array([ 1, 16, 16, ..., 50, 50, 50])

In [11]:
ranges: np.ndarray = np.array([1, 2, 9, 23, 40, 70, 90, 128, 180, 400])
def get_cluster_index(instance_number: int) -> int:
    
    # for idx, r in enumerate(ranges):
    #     if instance_number <= r:
    #         return idx
    return -1

In [12]:
ranges >= 2

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [102]:
from typing import List


def get_index_pos(bool_array: np.bool_) -> int:
    val =  np.where(bool_array == True)
    if val[0].size == 0:
        return 10
    return val[0][0]

index_pos_vec = np.vectorize(get_index_pos)

In [103]:
bool_list = np.bool_([0, 1, 1, 1])
# print(bool_list.shape)
get_index_pos(bool_list)

1

In [104]:
bool_list_test = np.bool_([0, 0])
get_index_pos(bool_list_test)

10

In [105]:
instance_indices = instances.apply(lambda x: get_index_pos(x <= ranges))
ser = pd.Series(instance_indices)

In [106]:
dummies = pd.get_dummies(ser)
dummies.rename(columns={col: f'inst_clust_{col}' for col in dummies.columns}, inplace=True)
dummies

inst_clust_0  inst_clust_1  inst_clust_2  inst_clust_3  inst_clust_4  \
0                   1             0             0             0             0   
1                   0             0             0             1             0   
2                   0             0             0             1             0   
3                   0             0             0             1             0   
4                   0             0             0             1             0   
...               ...           ...           ...           ...           ...   
1367426             0             0             0             0             0   
1367427             0             0             0             0             0   
1367428             0             0             0             0             0   
1367429             0             0             0             0             0   
1367430             0             0             0             0             0   

         inst_clust_5  inst_clust_6  inst_clust_7  inst_clust_8  inst_clust_9  \
0                   0             0             0             0             0   
1                   0             0             0             0             0   
2                   0             0             0             0             0   
3                   0             0             0             0             0   
4                   0             0             0             0             0   
...               ...           ...           ...           ...           ...   
1367426             1             0             0             0             0   
1367427             1             0             0             0             0   
1367428             1             0             0             0             0   
1367429             1             0             0             0             0   
1367430             1             0             0             0             0   

         inst_clust_10  
0                    0  
1                    0  
2                    0  
3                    0  
4                    0  
...                ...  
1367426              0  
1367427              0  
1367428              0  
1367429              0  
1367430              0  

[1367431 rows x 11 columns]

In [107]:
inst_df = training_df.join(dummies)
inst_df

start_date  inst_num   cpu_usage  gpu_wrk_util  \
0        1970-01-19 17:24:53+08:00       1.0  773.050807     12.648778   
1        1970-01-20 15:06:05+08:00      16.0  608.671034    192.687750   
2        1970-01-20 15:06:05+08:00      16.0  608.102445    192.662726   
3        1970-01-20 15:06:06+08:00      16.0  385.129135    190.093625   
4        1970-01-20 15:06:37+08:00      16.0  614.094135    193.115833   
...                            ...       ...         ...           ...   
1367426  1970-03-03 01:10:34+08:00      50.0   29.523810      0.750000   
1367427  1970-03-03 01:10:34+08:00      50.0   30.380952      0.666667   
1367428  1970-03-03 01:10:34+08:00      50.0   28.047619      0.958333   
1367429  1970-03-03 01:10:34+08:00      50.0   22.071429      1.666667   
1367430  1970-03-03 01:10:34+08:00      50.0   24.416667      0.250000   

           avg_mem    max_mem  avg_gpu_wrk_mem  max_gpu_wrk_mem  plan_cpu  \
0        19.953011  20.825195         4.266602         4.266602     400.0   
1        14.726125  29.648438        30.607422        30.607422     600.0   
2        14.808974  29.830078        30.607422        30.607422     600.0   
3        14.586163  29.396484        30.607422        30.607422     600.0   
4        14.683479  29.597656        30.607422        30.607422     600.0   
...            ...        ...              ...              ...       ...   
1367426   3.201766   4.047852         0.641724         5.735352     600.0   
1367427   3.225034   4.050781         0.805623         5.731445     600.0   
1367428   3.127250   3.985352         0.808390         5.735352     600.0   
1367429   3.631165   4.068359         1.458767         5.731445     600.0   
1367430   3.198730   3.601562         1.570190         5.731445     600.0   

          plan_mem  ...  inst_clust_1  inst_clust_2  inst_clust_3  \
0        10.000000  ...             0             0             0   
1        29.296875  ...             0             0             1   
2        29.296875  ...             0             0             1   
3        29.296875  ...             0             0             1   
4        29.296875  ...             0             0             1   
...            ...  ...           ...           ...           ...   
1367426  29.296875  ...             0             0             0   
1367427  29.296875  ...             0             0             0   
1367428  29.296875  ...             0             0             0   
1367429  29.296875  ...             0             0             0   
1367430  29.296875  ...             0             0             0   

         inst_clust_4  inst_clust_5  inst_clust_6  inst_clust_7  inst_clust_8  \
0                   0             0             0             0             0   
1                   0             0             0             0             0   
2                   0             0             0             0             0   
3                   0             0             0             0             0   
4                   0             0             0             0             0   
...               ...           ...           ...           ...           ...   
1367426             0             1             0             0             0   
1367427             0             1             0             0             0   
1367428             0             1             0             0             0   
1367429             0             1             0             0             0   
1367430             0             1             0             0             0   

         inst_clust_9  inst_clust_10  
0                   0              0  
1                   0              0  
2                   0              0  
3                   0              0  
4                   0              0  
...               ...            ...  
1367426             0              0  
1367427             0              0  
1367428             0              0  
1367429           

In [108]:
inst_df.to_csv('datasets/df_instance.csv')